world: "ffa"

timers:
  normal: 600
  ultimate: 900

drop-height: 250

locations:
  - "36 72 -41"
  - "61 70 -14"
  - "62 69 18"
  - "50 70 45"
  - "58 70 61"
  - "64 82 77"
  - "61 84 86"
  - "59 97 96"
  - "59 80 100"
  - "48 70 89"
  - "26 70 57"
  - "12 69 50"
  - "-9 75 23"
  - "48 96 21"
  - "25 70 -10"
  - "19 69 -50"
  - "-3 75 -49"
  - "-4 88 -23"
  - "0 96 2"
  - "41 92 105"
  - "-21 72 47"
  - "-36 70 48"
  - "-39 88 71"
  - "-59 71 78"
  - "-79 68 99"
  - "-118 76 94"
  - "-109 72 47"
  - "-110 71 29"
  - "-106 95 17"
  - "-114 95 23"
  - "-130 66 -2"
  - "-107 70 -8"
  - "-131 81 -21"
  - "-128 64 -47"
  - "-128 63 -58"
  - "-131 63 -73"
  - "-82 70 -65"
  - "-87 69 -32"
  - "-88 73 -0"
  - "-32 70 24"
  - "-40 70 5"
  - "-79 73 -9"
  - "-59 75 -66"
  - "-37 69 -67"
  - "-41 71 -55"
  - "-35 77 -35"
  - "-34 86 -42"
  - "-33 83 -21"
  - "-68 69 37"
  - "-25 104 4"
  - "3 100 -23"